/**
 * render.ts — Render a Pattern's TS module as human-readable Markdown.
 *
 * The `.ts` is the source of truth. The `.md` is a generated view —
 * never hand-edited. Useful when maestro wants to show the pattern to
 * the user during the debate, or when reading at a glance is easier
 * than scanning a TS module.
 *
 * Round-trip is one-way: TS → MD. There is no MD parser.
 */

import type { Pattern } from "./types";

function formatRequiredContext(req: readonly string[]): string {
  return req.length === 0 ? "(none)" : req.map((k) => `\`${k}\``).join(", ");
}

export function renderPatternMarkdown(pattern: Pattern): string {
  const ps = pattern.score;
  const lines: string[] = [];

  lines.push("---");
  lines.push(`pattern: ${ps.pattern}`);
  lines.push(`domain: ${ps.domain}`);
  lines.push(`description: ${pattern.description}`);
  lines.push(
    `required-context: ${pattern.requiredContext.length === 0 ? "[]" : `[${pattern.requiredContext.join(", ")}]`}`,
  );
  lines.push("---");
  lines.push("");
  lines.push(`# ${ps.pattern}`);
  lines.push("");
  lines.push(
    `> Generated from \`tools/patterns/${ps.pattern}.ts\`. Do not edit this file by hand — the TypeScript module is the source of truth.`,
  );
  lines.push("");
  lines.push("## Required context");
  lines.push("");
  lines.push(formatRequiredContext(pattern.requiredContext));
  lines.push("");
  lines.push("## Beats");
  lines.push("");
  ps.beats.forEach((b, i) => {
    lines.push(
      `${i + 1}. **${b.step}** \`(level ${b.level}, ${b.instrument})\` — ${b.directive}`,
    );
  });
  lines.push("");
  lines.push("## Annotation table");
  lines.push("");
  lines.push("| Step | Level | Instrument |");
  lines.push("|------|-------|------------|");
  for (const b of ps.beats) {
    lines.push(`| ${b.step} | ${b.level} | ${b.instrument} |`);
  }
  lines.push("");
  return lines.join("\n");
}
